# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('koef', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
