# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170505_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплачено: '),
        ),
    ]
